<a href="https://colab.research.google.com/github/Cademfitzgerald/Data-Science/blob/main/Cade_Fitzgerald_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [99]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [100]:
for i in range(5,8):
    print(i)

5
6
7


In [101]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


In [102]:
# How to print out numbers within a certain range with and without added words

### Functions

In [103]:
def square(x):
    return x**2

In [104]:
square(5)

25

In [105]:
square(square(2))

16

In [106]:
square(square(square(2)))


256

In [107]:
square(123456)

15241383936

In [108]:
square(square(5))

625

In [109]:
def add_two(x):
    return x+2

In [110]:
add_two(5)

7

In [111]:
square(add_two(5))

49

In [112]:
# How to change words into math problems with any variable

### Logical Branching

In [113]:
choice = "apple"

In [114]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [115]:
choice = "orange"

In [116]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [117]:
choice = "apple"

In [118]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


In [119]:
# How to give users multiple choice options

### User Input

In [120]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [121]:
# How to get someone's direct input

In [122]:
choice

'apple'

In [123]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [124]:
np.random.random()

0.42178692050461475

In [125]:
np.random.random() > 0.5

False

In [126]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [127]:
flip_coin()

Tails


In [128]:
# How to make a coin flip randomizer 

### Graphics Output

In [129]:
import numpy as np

In [130]:
from IPython.core.display import display, HTML

In [131]:
display(HTML('<h1>Hello, world!</h1>'))

In [132]:
def coin():
  return np.random.randint(2)

In [133]:
coin()

1

In [134]:
# How to link the randomized coin flipper to show matching heads and tails images

In [135]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [136]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [137]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [138]:
show_img(heads)

In [139]:
show_img(tails)

In [140]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [141]:
flip_coin()

In [142]:
for i in range(5):
    flip_coin()

In [143]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [144]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [145]:
a = np.arange(52)

In [146]:
# How to get a random set of numbers

In [147]:
shuffle(a)

array([25,  9, 12, 13,  2, 31, 46, 29,  3, 44, 24, 32, 42, 28, 50, 45, 17,
       41,  0, 18,  7, 22, 10,  6, 37,  4, 48, 16, 47, 15, 34, 26, 49, 36,
       11, 39, 40, 27, 35, 20, 33, 14,  5, 19, 51, 30, 38, 21,  1,  8, 23,
       43])

In [148]:
np.random.permutation(52)

array([27, 47, 17, 26,  2, 24, 40, 39,  7, 51, 25, 45, 31, 18, 20, 15, 43,
       35,  5,  9, 13, 36, 46, 42,  8,  1, 33,  3, 38, 10, 29, 28, 16, 21,
       11, 22, 32, 19, 14, 49, 44, 37, 41, 50, 30,  4, 12, 23,  6, 34, 48,
        0])

### Speed Test

In [149]:
%%timeit
shuffle(a)

124 µs ± 2.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [150]:
%%timeit
np.random.permutation(52)

2.47 µs ± 93.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [151]:
import numpy as np

In [152]:
np.random.permutation(52)

array([48, 13, 34,  5, 23, 50, 39, 18,  7, 15, 30, 31, 27, 44, 32,  2,  4,
        0, 25,  6, 49, 33,  3, 41, 45, 37, 40, 46, 19, 22, 14, 10,  8,  9,
       12, 11, 26, 20,  1, 29, 47, 36, 16, 17, 42, 28, 38, 35, 43, 24, 21,
       51])

In [153]:
cards = np.random.permutation(52)

In [154]:
cards

array([26, 35, 24, 16,  8, 43, 15,  3, 34, 13, 23, 11, 48,  2, 20,  1, 37,
        0, 40, 51, 28, 30, 31, 44, 33, 12, 49, 17, 36, 45, 27, 47, 22, 38,
       32, 39, 41, 10, 42,  7,  4, 46, 29, 19, 50, 21, 14,  5, 25, 18,  6,
        9])

In [155]:
cards[0]

26

In [156]:
cards[1]

35

In [157]:
cards[2]

24

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [158]:
# How to import an image with a text box

In [159]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [160]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [161]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [162]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [163]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [164]:
card_name(0)

'Ace of Clubs'

In [165]:
card_name(51)

'King of Diamonds'

In [166]:
# How to sort the cards

In [167]:
cards = np.random.permutation(52)

In [168]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [169]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Jack of Hearts', 'Eight of Diamonds', 'Two of Diamonds')

In [170]:
for i in range(5):
    print(card_name(cards[i]))

Jack of Hearts
Eight of Diamonds
Three of Hearts
Jack of Spades
Seven of Hearts


In [171]:
for i in range(15):
    print(card_name(cards[i]))

Jack of Hearts
Eight of Diamonds
Three of Hearts
Jack of Spades
Seven of Hearts
Nine of Diamonds
King of Diamonds
Ace of Spades
Six of Diamonds
Two of Hearts
Jack of Diamonds
Five of Spades
Queen of Diamonds
Three of Spades
Jack of Clubs


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [172]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [173]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [174]:
i = np.random.randint(4)
j = np.random.randint(13)

In [175]:
i,j

(1, 11)

In [176]:
suit[i]

'p'

In [177]:
card[j]

'q'

In [178]:
from IPython.core.display import display, HTML

In [179]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [180]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [181]:
show_img(img)

In [182]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [183]:
card_image(3)

'k4'

In [184]:
img = card_url_head + card_image(3) + card_url_tail

In [187]:
# How to get a random card with a matching image

In [185]:
show_img(img)

In [186]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)